server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: sample-route
          uri: http://sample-application:8081
          predicates:
            - Path=/sample/** 
          filters:
            - StripPrefix=1
            # Filtro de CircuitBreaker con fallback (configurable)
            - CircuitBreaker=name=sampleServiceCircuitBreaker,fallbackUri=forward:/fallback/sample
            # Filtro de Retry para métodos GET (configurable)
            - Retry=methods=GET,retries=3,backoff=100,1000,2,true
          metrics:
            enables: true

resilience4j:
  circuitbreaker:
    instances:
      samplingService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        minimumNumberOfCalls: 5
  timelimiter:
    instances:
      samplingService:
        timeoutDuration: 3s
