server:
  port: 8084

spring:
  application:
    name: frontend
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  
  # Importante: para que lea configuración remota
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      import-check:
        enabled: false
    # Habilita la comunicación con Spring Cloud Bus
    bus:
      enabled: true
    # Configuración del gateway
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: microusers-route
          uri: http://microusers:8081
          predicates:
            - Path=/api/users/**,/api/login
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: microusersCircuitBreaker
                fallbackUri: forward:/fallback/microusers
            - name: Retry
              args:
                retries: 3
                methods: GET,POST,PUT,DELETE
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 1000ms
                  factor: 2
                  
        - id: microproducts-route
          uri: http://microproducts:8083
          predicates:
            - Path=/api/products/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: microproductsCircuitBreaker
                fallbackUri: forward:/fallback/microproducts
            - name: Retry
              args:
                retries: 3
                methods: GET,POST,PUT,DELETE
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 1000ms
                  factor: 2

        - id: microorders-route
          uri: http://microorders:8082
          predicates:
            - Path=/api/orders/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: microordersCircuitBreaker
                fallbackUri: forward:/fallback/microorders
            - name: Retry
              args:
                retries: 3
                methods: GET,POST,PUT,DELETE
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 1000ms
                  factor: 2
                  
      metrics:
        enabled: true

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default,chaos-monkey}

# Configuración de Resilience4j
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 100
        minimumNumberOfCalls: 20
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s  # Actualizado a 10s
        failureRateThreshold: 20  # Actualizado a 20
        eventConsumerBufferSize: 20
    instances:
      microusersCircuitBreaker:
        baseConfig: default
      microproductsCircuitBreaker:
        baseConfig: default
      microordersCircuitBreaker:
        baseConfig: default

# Configuración de Chaos Monkey
chaos:
  monkey:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    chaosmonkey:
      enabled: true
    gateway:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
