server:
  port: 8888

spring:
  application:
    name: config-server
  kafka:
    # IMPORTANTE: desde DENTRO del contenedor, Kafka se llama "kafka:9092"
    bootstrap-servers: kafka:9092
  consumer:
    group-id: config-server
    auto-offset-reset: earliest

  # Ajusta si usas spring.cloud.stream, etc.
  # Si no, quita la parte de consumer

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dvmc13/config-repo.git
          default-label: main
          clone-on-start: true
          search-paths: '{application}'
    bus:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
