server:
  port: 8888

spring:
  application:
    name: config-server
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: config-server
      auto-offset-reset: earliest

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dvmc13/config-repo.git
          default-label: main
          clone-on-start: true
          search-paths: '{application}'
    bus:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
