server:
  port: 8085

spring:
  kafka:
    consumer:
      group-id: rule-engine-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.resilience.model"

prometheus:
  server: http://prometheus:9090
  metrics:
    scan-interval: 30000  # 30 segundos

resilience:
  webhook:
    endpoint: http://resilience-core:8084/api/actions
  rules:
    error-rate-threshold: 0.1
    latency-threshold-ms: 2000
    request-volume-threshold: 500
    connection-failure-threshold: 5
