server:
  port: 8082  # Cambiado a 8082 para evitar conflicto con microproducts

spring:
  application:
    name: microorders
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default,chaos-monkey}
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      import-check:
        enabled: false
    bus:
      enabled: true
  datasource:
    url: jdbc:mysql://mysql:3306/microorders_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: microorders
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    chaosmonkey:
      enabled: true
  health:
    circuitbreakers:
      enabled: true

# Configuración de Resilience4j
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
    instances:
      ordersService:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1s
  ratelimiter:
    configs:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0s

# Configuración de Chaos Monkey
chaos:
  monkey:
    enabled: false
    watcher:
      controller: true
      restController: true
      repository: false
      service: true
      component: false
    assaults:
      latencyActive: false
      exceptionsActive: true
      killApplicationActive: false
      level: 3
      latencyRangeStart: 1000
      latencyRangeEnd: 3000
