server:
  port: 8082 

spring:
  application:
    name: microorders
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default,chaos-monkey}
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      import-check:
        enabled: false
    bus:
      enabled: true
  datasource:
    url: jdbc:mysql://mysql:3306/microorders_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: microorders
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    chaosmonkey:
      enabled: true
    ratelimiters:
      enabled: true
    ratelimiterevents:
      enabled: true
  health:
    ratelimiters:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        resilience4j.ratelimiter: true

resilience4j:
  ratelimiter:
    instances:
      microordersRateLimiter:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
        timeoutDuration: 3s
        registerHealthIndicator: true
        eventConsumerBufferSize: 100

# Configuración de Chaos Monkey
chaos:
  monkey:
    enabled: true
    watcher:
      controller: true
      restController: true
      service: true
      repository: true
      component: true
    assaults:
      latencyActive: true
      exceptionsActive: false
      killApplicationActive: false
      level: 5  # Alto nivel para aumentar probabilidad
      latencyRangeStart: 1000
      latencyRangeEnd: 3000
      deterministic: false  # Modo aleatorio
      exceptions:
        type: java.lang.RuntimeException
        arguments:
          - "Chaos Monkey - RuntimeException en microorders"
