server:
  port: 8082  # Cambiado a 8082 para evitar conflicto con microproducts

spring:
  application:
    name: microorders
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default,chaos-monkey}
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      import-check:
        enabled: false
    bus:
      enabled: true
  datasource:
    url: jdbc:mysql://mysql:3306/microorders_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: microorders
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    chaosmonkey:
      enabled: true
  health:
    circuitbreakers:
      enabled: true

# Configuración de Chaos Monkey
chaos:
  monkey:
    enabled: false
