server:
  port: 8090

spring:
  application:
    name: resilience-service

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: resilience-service-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: RECORD
      missing-topics-fatal: false

kafka:
  topics:
    config-changes: config-changes-topic
    resilience-actions: resilience-actions-topic

resilience:
  monitoring:
    enabled: true
    rate: 60000
    thresholds:
      latency: 500
      error-rate: 10

# Ejemplo de patrones predefinidos
resilience-patterns:
  circuit-breaker:
    default:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 5000
    high-sensitivity:
      slidingWindowSize: 5
      failureRateThreshold: 30
      waitDurationInOpenState: 10000
  retry:
    default:
      maxAttempts: 3
      waitDuration: 1000
    aggressive:
      maxAttempts: 5
      waitDuration: 500
  rate-limiter:
    default:
      limitForPeriod: 10
      limitRefreshPeriod: 1000
      timeoutDuration: 3000
    restrictive:
      limitForPeriod: 5
      limitRefreshPeriod: 2000
      timeoutDuration: 1000
